### ISSUE TITLE
Add Dash Bootstrap Components

### ISSUE THREAD

**Issue by andresgarciaf** [MaaniBeigy/dash-boilerplate#3]
## 🚀 Feature Request

Can Dash Bootstrap Components be added, for fast development. https://dash-bootstrap-components.opensource.faculty.ai/
Or a guide to add new libraries to the project when forked.

## 🔈 Motivation

This will provide faster development on components and a popular framework for components.

**Comment by MaaniBeigy** [comment]
@jgarciaf106 
Of course, you can add any dependency you need to your `pyproject.toml`.

However, it should be noted, three different modes are considered in this boilerplate: 

1. development (dockerized),
2. production (dockerized), 
3. github actions (i.e., CI using Makefile). 

The development and production dockers use [https://github.com/MaaniBeigy/dash-boilerplate/blob/main/lib/web/pyproject.toml](https://github.com/MaaniBeigy/dash-boilerplate/blob/main/lib/web/pyproject.toml)  as `pyproject.toml`, while the github actions or local testing with Makefile use the  `pyproject.toml` in the parent directory [https://github.com/MaaniBeigy/dash-boilerplate/blob/main/pyproject.toml](https://github.com/MaaniBeigy/dash-boilerplate/blob/main/pyproject.toml).

If you want to add dependencies, you have to include them in both mentioned files. 

Finally, and due to the paramount role of `dash-bootstrap-components` in dash applications, I will add it as a default dependency of this boilerplate.

Regards,
Maani

**Comment by andresgarciaf** [comment]
@MaaniBeigy Thanks for replying and guidance.

Great work on this boilerplate.
